### ISSUE TITLE
示例代码有误

### ISSUE THREAD

**Issue by lizhongzhen11** [doodlewind/jshistory-cn#11]
https://github.com/doodlewind/js-20-years-cn/blob/master/part-2.md#%E6%B5%8F%E8%A7%88%E5%99%A8%E5%8D%9A%E5%BC%88%E8%AE%BA 浏览器博弈论 上面的代码有误

即
```js
// 使用模块模式定义 services
var Services = function () {
  var privateJobCount = 0; // 「模块」的私有状态
  return { // 命名空间对象
    jobCount: function {return privateJobCount},
    job1: function() {this.jobCount++}
  }
}(); // Services 被初始化为调用该函数时的返回值

// 从命名空间里获取实体
Services.job1();
console.log(Services.jobCount()); // 显示 1
```

首先 `jobCount: function {return privateJobCount}` 这里 `function` 后面缺少 `()`
其次，应该是 `job1: function() {privateJobCount++}` 吧？

最终代码是不是这样的？
```js
var Services = function () {
  var privateJobCount = 0; // 「模块」的私有状态
  return { // 命名空间对象
    jobCount: function() {return privateJobCount},
    job1: function() {privateJobCount++}
  }
}(); // Services 被初始化为调用该函数时的返回值
Services.job1();
console.log(Services.jobCount());
```

**Comment by doodlewind** [comment]
你好


谢谢你的指正，这应该属于原文代码示例的 bug，我在译文中已经修改了。后面待 Part 4 完成后，准备一并将勘误表反馈给原作者 :D 如果找到其他问题，也欢迎你的反馈！


Regards
雪碧




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "doodlewind/js-20-years-cn"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月22日(星期三) 下午3:01
收件人:&nbsp;"doodlewind/js-20-years-cn"<js-20-years-cn@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[doodlewind/js-20-years-cn] 示例代码有误 (#11)





 
https://github.com/doodlewind/js-20-years-cn/blob/master/part-2.md#%E6%B5%8F%E8%A7%88%E5%99%A8%E5%8D%9A%E5%BC%88%E8%AE%BA 浏览器博弈论 上面的代码有误
 
即
 // 使用模块模式定义 services var Services = function () {   var privateJobCount = 0; // 「模块」的私有状态   return { // 命名空间对象     jobCount: function {return privateJobCount},     job1: function() {this.jobCount++}   } }(); // Services 被初始化为调用该函数时的返回值 // 从命名空间里获取实体 Services.job1(); console.log(Services.jobCount()); // 显示 1
 
首先 jobCount: function {return privateJobCount} 这里 function 后面缺少 ()
 其次，应该是 job1: function() {privateJobCount++} 吧？
 
最终代码是不是这样的？
 var Services = function () {   var privateJobCount = 0; // 「模块」的私有状态   return { // 命名空间对象     jobCount: function() {return privateJobCount},     job1: function() {privateJobCount++}   } }(); // Services 被初始化为调用该函数时的返回值 Services.job1(); console.log(Services.jobCount());
