### ISSUE TITLE
标题翻译问题

### ISSUE THREAD

**Issue by flyyang** [doodlewind/jshistory-cn#13]
The first 说的是第一个20年。开篇标题翻译不太准确，内容吸引力就降低了。

**Comment by doodlewind** [comment]
你好，这里的问题在于，"first" 是一个有强需求被保留的概念吗？

我们会根据实际的语境，去增加或删减语言成分，从而接近中文的语言习惯。据我自己的用语习惯，下面这两种表述：

* 《JavaScript 前 20 年史》
* 《JavaScript 前 20 年》

相比起

* 《JavaScript 20 年史》
* 《JavaScript 20 年》

前面两者似乎并不常见。就 JavaScript 来说，也没有「前 20 年」和「后 20 年」这样的歧义（我们会默认会从创建起开始吧）。如果陈述所能传递的信息是同等的，那么并不必保证逐字逐句层面的一致（否则会有明显的翻译腔问题）。

另外，Allen Wirfs-Brock 在正文完成后其实已经给过了 review 意见，我也据此调整了部分一二级章节的标题名，但没有收到针对全文名称的反馈。

不过这里只是陈述我的理解，对于「理想中的标题名」我也是持开放的态度哈。如果你觉得有更好的标题，也希望可以告知。

**Comment by doodlewind** [comment]
cc @allenwb How's your idea that if the "First" word in title contains message worth preserving?

Also, there was a suggestion from co-publisher that "JavaScript 20 年传" (translated back as "JavaScript: 20 Years Biography") could be used as an alternative, and that the word "biography" in Chinese would increase its authority and collection value. Wondering if you think it acceptable? Thanks.

**Comment by flyyang** [comment]
>《JavaScript: The First 20 Years》以上百页的篇幅，详细记述了 JavaScript 自 1995 至 2015 年间的演化故事。本项目将尝试搬运其内容到中文社区，方便更多同学接触这份兼有收藏与研究价值的史料。

The first 20 years，直译过来是第一个20年，对应1995-2015的时间线，the 有强调的意思。

《JavaScript 20 年》、《JavaScript 20 年史》，丢了first，就无法说清时间线，不够达。

我也觉得直译 《JavaScript: 第一个 20年》，不够雅。但是相对以上两个有以下两个优点：

1. 直接表明了时间线。
2. JavaScript 还有下一个20年，下一个100年等，暗示 JavaScript 的生命力顽强。

以上只是抛转，供参考。

**Comment by allenwb** [comment]
I don't think ''first" is essential. It was there to distinguish it from future histories covering later periods.

How about the equivalent of:
JavaScript Biography: 1995 to 2015

(Of course in English I would use "history" instead of "biography")

**Comment by flyyang** [comment]
I like JavaScript Biography: 1995 to 2015.

Clear and precise.
