### ISSUE TITLE
一处单词拼写错误

### ISSUE THREAD

**Issue by holyzfy** [doodlewind/jshistory-cn#14]
首先感谢作者的辛苦翻译。

[part-1.md#从-mocha-到-spidermonkey](https://github.com/doodlewind/jshistory-cn/blob/master/part-1.md#%E4%BB%8E-mocha-%E5%88%B0-spidermonkey) 章节`图 10. JavaScript 1.2 的新特性`里

> * 新数组方法 push, pop, shift, unshift, solice, concat, slice

此处`solice`应该是`splice`吧

**Comment by doodlewind** [comment]
谢谢，已经修复 :)
