### ISSUE TITLE
静态站美化与章节拆分

### ISSUE THREAD

**Issue by esmadrider** [doodlewind/jshistory-cn#16]
Hi! 感谢辛苦的翻译！我最近也从头到尾看完了，亲眼见证最近 Star 数蹭蹭的往上涨，挺激动。

在阅读过程中，也看到了 [cn.history.js.org](https://cn.history.js.org/) 的正式启动，现在总算有个静态页面咯。

我最近使用的 [Pagic](https://pagic.org/) 建站工具感觉用来部署这本书的在线版本会很好！

* 支持**中英文双语言**：同时部署两个英文原版和中文翻译版；
* 支持左侧**导航条**查看：很方便进行导航式浏览，同时拆分章节目录（现在每章一页太庞大）；
* 支持**白色/夜间主题**：符合现在的多主题潮流；
* **很少的仓库侵入式**：只需一个 `pagic.config.tsx` 在根目录 + github actions 就可以持续部署；
* **支持官网首页**：这样到时候国内出版书的话首页宣传起来也更酷；
* **支持评论区**：互相交流，社区友好，实体书卖的更好 😍；
* **统计页面浏览量**：方便知道有多少人关注，思考用户转化率；
* **Deno + React** 技术支持：React as Pages 的想法，到时候拓展页面内容的话写 tsx 就好；
* ...

我自己的一本电子书也已经通过 Pagic 上线咯 -> http://deno-tutorial.js.org。

所以，用 Pagic 来美化界面，怎么样呢？**我可以帮忙提交相关 PR，到时候只需要一个简单的合并就好咯。**

P.S: 我发现翻译后的文章里大部分标题都没有原文里类似于 `5.1.1` 这种目录，我也可以帮忙一次性加上，怎么样哈？

![](https://user-images.githubusercontent.com/19285461/94238779-6de77b00-ff43-11ea-8354-4d0030a6ce25.png)

期待回复 👍🏿

**Comment by doodlewind** [comment]
你好，我个人对在线版的预期是对齐 [You Don't Know JS](https://github.com/getify/You-Dont-Know-JS) 的（以 GitHub 上持续维护的页面为主，最低限度的「额外美化」），因此之前希望提供的其实就是现在的阅读体验，接下来精力主要是纸质版和修订上。

进一步拆分章节并引入静态站点生成器的话，有一个潜在的风险，即虽然它本身侵入性不强，但拆分后大量的参考文献、脚注、术语表等链接地址又需要手工的转换和确认（苦力活，并且从其他站点来的外链也可能失效），所以没有特别理由的话我倾向于先不折腾它……当然这个 issue 就先开着吧，如果大家有其他反馈和建议也欢迎哈。

**Comment by esmadrider** [comment]
👍 最低限度地美化这主意确实不错，看你们和编辑社的考量了。

不过人工检查、手工转换以及章节拆分的话，我可以提 PR，可以的话我就开搞 🤡

对于我来说，特别理由就是：用更好的静态网站更直观，更容易通过目录的编排复习甚至多看几遍，哈哈 😄

对了，还支持评论区，可以留言～首页同时宣传实体版纸质书，会卖的更好！


所以￼￼...看起来我可以提交个 PR 试试 😁

**Comment by doodlewind** [comment]
实际上 LaTeX 版是单个文件写完的，再鉴于部分章节实际上非常短，所以我不确定拆得更细是否会更好 :(

至于评论区等功能的话，GitHub 的 Issue 就够了呀。最好的一点是你可以在这里 at 到 [allenwb](https://github.com/allenwb)，直接和他交流你对内容本身的疑问 👻

**Comment by flyingcrp** [comment]
.cn上的,章节目录应该和内容分开,最好是可以在任意,做成导航一样的方式

**Comment by doodlewind** [comment]
静态站已经更新，谢谢 @hylerrix 与 @xcatliu 的支持！

向 @xcatliu 反馈 Pagic 中一些已知的链接跳转问题：

1. 形如 `<a href="./notes.md">` 的格式无法被正确解析，如第一章的「循环垃圾回收<sup>g</sup>」术语表链接
2. 文字符号转义规则与 GitHub 不一致，如对于 part-1.md 中的 `插曲：风评被害` 章节名，GitHub 会将其转为 `part-1.html#插曲风评被害`，而 Pagic 会转为 `#插曲：风评被害`，类似的还有章节 `JavaScript 1.0 与 1.1`，GitHub 转为 `#javascript-10-与-11`，而 Pagic 则转为 `#javascript-1.0-与-1.1`。GitHub 这里应该多过滤了一层全半角字符。
3. H1 标签无法被 anchor 到。
4. H4 标签未计入页面右侧的 Table of Content。

问题 1-3 会导致 GitHub 项目中的目录（[jshistory-cn](https://github.com/doodlewind/jshistory-cn)）链接与 Pagic 静态站的链接只有一个可用（要么编写适应 GitHub 风格的链接，要么编写适应 Pagic 风格的链接），是否有考虑对齐一下呢？

**Comment by xcatliu** [comment]
@doodlewind 已记录到 [Pagic 1.0 的 TODOs](https://github.com/xcatliu/pagic/projects/3) 中

1. 会修复
2. 会向 github 靠齐
3. 会提供一个选项
4. 会提供一个选项

**Comment by esmadrider** [comment]
哈哈，祝贺 JavaScript 20 年 中文版 新的静态页面发布 🥳 （成功混了个 committer…
