### ISSUE TITLE
请检查一处单词拼写

### ISSUE THREAD

**Issue by holyzfy** [doodlewind/jshistory-cn#17]
[part-3.md](https://github.com/doodlewind/jshistory-cn/blob/master/part-3.md) 第一段

> ...
> Web 的成功与其持续演化的诉求，催生了 Ecma TC39 和 W3G 等工作组。
> ...

此处`W3G`应是`W3C`吧？

**Comment by doodlewind** [comment]
你好，此处应当系原文笔误，已经修正，谢谢！
