### ISSUE TITLE
我刚刚打算把这个文档部署到自己的服务器上的时候，报以下错误

### ISSUE THREAD

**Issue by AlpacaBi** [doodlewind/jshistory-cn#23]
这个是否与pagic版本有关系？？？
![pic](https://cdn.alpaca.run/default/e.png)

**Comment by doodlewind** [comment]
尝试改用 Pagic 的 `0.9.8` 版本吗？

```
deno install --unstable --allow-env --allow-read --allow-write --allow-net -n pagic https://deno.land/x/pagic@v0.9.8/mod.ts
```

**Comment by AlpacaBi** [comment]
> 尝试改用 Pagic 的 `0.9.8` 版本吗？
> 
> ```
> deno install --unstable --allow-env --allow-read --allow-write --allow-net -n pagic https://deno.land/x/pagic@v0.9.8/mod.ts
> ```

thanks，改用此版本后功能正常，问题已解决

**Comment by doodlewind** [comment]
cc @xcatliu

**Comment by xcatliu** [comment]
可以用最新版 v0.10.1
