### ISSUE TITLE
Babel 这段翻译不对， “我推送到 GitHub 上的第一次提交，是为了一个我在高考复习时正在做的 JavaScript 库。”

### ISSUE THREAD

**Issue by qiulang** [doodlewind/jshistory-cn#29]
原文是 On September 28th 2014 I pushed my first commit to GitHub for a JavaScript library I was working on while studying for my high school exams. 我在复习高中考试的同时提交了 GitHub 上的第一次commit，不是  **是为了一个我在高考复习时正在做的 JavaScript 库**

**Comment by doodlewind** [comment]
谢谢反馈！此处表述已经优化
