### ISSUE TITLE
如何参与翻译

### ISSUE THREAD

**Issue by JerryYuanJ** [doodlewind/jshistory-cn#5]
RT，是直接提PR么？但是不知道会不会和你的翻译进度有冲突。

**Comment by doodlewind** [comment]
你好，参与当然欢迎。但希望理解我个人对格式有些「洁癖」，如果需要为大篇幅与我个人风格不太符合的内容润色，我可能会感到为难。可否尝试试译一小段呢？

这是 Part 4 中 20.1.2 节的内容：

*Getters, Setters, Object Meta Operations*. Beginning with the first implementations of JavaScript, some properties of certain built-in and host-provided objects had special characteristics that were not available for objects created using JavaScript code. For example, some properties had read-only values or could not be deleted using the `delete` operator, and method properties of built-in and host objects are skipped when enumerating properties using the `for-in` statement. In ES1, these special semantics were specified by associating ReadOnly, DontDelete, and DontEnum attributes with the specification’s model of object properties. These attributes are tested by the pseudocode which defines the semantics of language features which are sensitive to them. These attributes are not reified—there were no language features that enabled JavaScript code to set these attributes for either newly created or preëxisting properties. ES3 added an `Object.prototype.propertyIsEnumerable` method for testing for the presence of the DontEnum attribute, but there were no corresponding methods for non-destructively testing for the ReadOnly or DontDelete attributes. Similarly, many of the host objects provided by the browser DOM expose properties, typically called “getter/setter properties” but christened “accessor properties” by ES5, which perform computations when the value of the property is set or retrieved. The lack of standardized support for these features made it impossible for JavaScript programmers to define libraries that follow the same conventions as the built-in or host objects or to implement polyfills which faithfully emulate such objects.

没有时间限制，OK 后还请发送内容到我的邮箱（否则可能对后来者会有先入为主的影响）😀

另外，这个要求只面向希望贡献章节级内容的同学，对已有内容的修订建议随时欢迎 Issue 和 PR 哈。

**Comment by MoliZHOU** [comment]
@doodlewind 我也有意参加翻译工作，请问是否也可以用以上片段做尝试呢？格式上有具体的要求吗？

**Comment by doodlewind** [comment]
@MoliZHOU 可以，希望行文格式与当前文章尽量保持一致吧（发送到我的邮箱即可）。

**Comment by doodlewind** [comment]
目前章节已经过半且找到了协作者，这个 Issue 可以关闭了。感谢热心同学的尝试 🙏
