### ISSUE TITLE
GitBook 与 PDF 格式支持

### ISSUE THREAD

**Issue by RtYkk** [doodlewind/jshistory-cn#7]
方便阅读

**Comment by doodlewind** [comment]
你好，现在还处于用基础的 markdown 赶内容的阶段，图表使用了截图，并且缺乏参考文献引用链接。待全文完成后，我会继续优化版式提供 PDF 支持的哈。

**Comment by doodlewind** [comment]
Update: 几个月来我们已经大幅优化了在线版格式（详见[更新介绍](https://zhuanlan.zhihu.com/p/257990478)），解决了上述格式问题。但鉴于与未来纸质版相关的考量，参考 [You don't know JS](https://github.com/getify/You-Dont-Know-JS) 的形式，这个仓库将不会进一步开源其他格式的版本。但请放心，在线版仍然会保持更新维护，始终可自由阅读，希望你可以理解 :)

**Comment by hunter524** [comment]
https://github.com/shd101wyy/markdown-preview-enhanced  只能自己用这个工具生成 epub,pdf 等其他格式文件了
